### ISSUE TITLE
Autocompletion on elixir 1.4 not working

### ISSUE THREAD

**Issue by ankos** [mat-mcloughlin/vscode-elixir#45] opened 2017-01-17 16:35 UTC
I am a bit at a loss regarding how to fix this. The plugin is working flawless on Windows, but on Linux (Mint 18.1, Elixir 1.4) the autocompletion does not work.
Tried to things to find out whats wrong:
1. Started the alchemist-server which comes along with the plugin. It produces a lot of warnings and the code examples shown on the github page are not working. Example:
```
COMP { "def", [ context: Elixir, imports: [Enum], aliases: [{MyList, List}] ] }
Server Error: 
no match of right hand side value: {{"def", [context: Elixir, imports: [Enum], aliases: [{MyList, List}]]}, []}
    lib/api/comp.exs:42: Alchemist.API.Comp.normalize/1
    lib/api/comp.exs:15: Alchemist.API.Comp.request/1
    lib/server.exs:59: Alchemist.Server.run/6
    lib/server.exs:39: Alchemist.Server.loop/5
    (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
    (elixir) src/elixir_compiler.erl:30: :elixir_compiler.quoted/3
    (elixir) lib/code.ex:370: Code.require_file/2
```
2. Cloned the code from the alchemist-server gist. Did the same thing and it works as expected.

**Comment by fr1zle** [comment] 2017-01-18 08:55
It seems to work for me on Fedora 25 and Ubuntu LTS.
Can you open the Developer Tools (via Help) and see if there are any errors in there?

The Version of our included alchemist-server may not be compatible with the latest version in the upstream git.

**Comment by ankos** [comment] 2017-01-18 17:15
Two things I can see:

1.) Errors during the start: also copied the log message that the included alchemist server displays while starting.

```
[Extension Host] [vscode-elixir] server started Object

[Extension Host] [vscode-elixir] error: arboting command warning: this clause cannot match because a previous clause at line 94 always matches
  /home/ankos/.vscode/extensions/mjmcloug.vscode-elixir-0.1.1/alchemist-server/lib/helpers/introspection.exs:94

[Extension Host] Uncaught Exception:  TypeError: _this.resultCallback is not a function 

[Extension Host] TypeError: _this.resultCallback is not a function
    at Socket.<anonymous> (/home/ankos/.vscode/extensions/mjmcloug.vscode-elixir-0.1.1/out/src/elixirServer.js:68:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

_this.resultCallback is not a function: TypeError: _this.resultCallback is not a function
    at Socket.<anonymous> (/home/ankos/.vscode/extensions/mjmcloug.vscode-elixir-0.1.1/out/src/elixirServer.js:68:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

[Extension Host] [vscode-elixir] error: arboting command warning: the variable "new_state" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  /home/ankos/.vscode/extensions/mjmcloug.vscode-elixir-0.1.1/alchemist-server/lib/code/state.exs:75
```

2.) Strange behavior whenever I'm trying to look something up. For example typing `Range. ` yields following error message. Every other module does the same thing:

```
[Extension Host] [vscode-elixir] cmd:  COMP { "Range.", "/home/ankos/Projects/discuss/web/controllers/topic_controller.ex", 40 }

[Extension Host] [vscode-elixir] error: arboting command warning: Enum.uniq/2 is deprecated, use Enum.uniq_by/2 instead
  (elixir) lib/enum.ex:2547: Enum.uniq/2
  /home/ankos/.vscode/extensions/mjmcloug.vscode-elixir-0.1.1/alchemist-server/lib/helpers/complete.exs:222: Alchemist.Helpers.Complete.expand_elixir_modules/3
  /home/ankos/.vscode/extensions/mjmcloug.vscode-elixir-0.1.1/alchemist-server/lib/helpers/complete.exs:27: Alchemist.Helpers.Complete.run/1
  /home/ankos/.vscode/extensions/mjmcloug.vscode-elixir-0.1.1/alchemist-server/lib/api/comp.exs:28: Alchemist.API.Comp.process/1
  /home/ankos/.vscode/extensions/mjmcloug.vscode-elixir-0.1.1/alchemist-server/lib/server.exs:59: Alchemist.Server.run/6
```

**Comment by fr1zle** [comment] 2017-01-19 07:36
@ankos thanks. I was able to reproduce this on elixir 1.4

Issue 1) should be solved with #24 Although this is not really an issue since the plugin runs fine on elixir 1.3.x and should do so in 1.4 if it wasnt for
Issue 2) this needs to be fixed in our alchemist-server 'fork', i will look into this as soon as i find some time.

**Comment by high1** [comment] 2017-01-25 15:35
I closed the issue #48 as a duplicate of this one, but this issue affects Windows also, so this is a Elixir 1.4 issue with alchemist-server really.

**Comment by fr1zle** [comment] 2017-01-25 16:27
@mat-mcloughlin now that elixir 1.4 gains momentum, i think we should merge #24 and #46 and release a new version.

**Comment by mat-mcloughlin** [comment] 2017-01-28 10:54
agreed. Run off my feet again but I'm gonna make some time over the weekend to pull everything together an publish

**Closed** 2017-01-28 14:43 UTC
Labels: bug
