### ISSUE TITLE
Weird autocomplete on "do"

### ISSUE THREAD

**Issue by thousandsofthem** [mat-mcloughlin/vscode-elixir#14] opened 2016-07-12 15:53 UTC
How to reproduce:
* Start writing new function
* Type `do`
* Hit enter
Editor will autocomplete do to full multiline `@doc` block

Expected:
Inserting new line, nothing fancy ;)

**Comment by philipgiuliani** [comment] 2016-07-13 06:40
This is a duplicate of https://github.com/mat-mcloughlin/vscode-elixir/issues/12 . Close and add a comment there ;)

**Closed** 2016-07-13 07:26 UTC
